### ISSUE TITLE
Vue Dependency Error when running "python3 server.py --insecure --build"

### ISSUE THREAD

**Issue by 0zk3y** [mitre/caldera#2886]
**Describe the bug**
Getting error as below of vue:
```
Copying all plugin GUI source files to magma
Copying over "access" files...
Copying over "atomic" files...
Copying over "builder" files...
Copying over "compass" files...
Copying over "debrief" files...
Copying over "emu" files...
Copying over "gameboard" files...
Copying over "human" files...
Copying over "manx" files...
Copying over "response" files...
Copying over "sandcat" files...
Copying over "ssl" files...
Copying over "stockpile" files...
Copying over "training" files...
Plugin GUI source files copied!
vite v2.9.15 building for production...
✓ 0 modules transformed.
[vite:vue] Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
error during build:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (/home/ubuntu/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:3955:11)
    at Object.buildStart (/home/ubuntu/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:4686:46)
    at /home/ubuntu/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:22834:37
    at async Promise.all (index 4)
    at async /home/ubuntu/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23622:13
    at async catchUnfinishedHookActions (/home/ubuntu/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23132:20)
    at async rollupInternal (/home/ubuntu/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23620:5)
    at async doBuild (/home/ubuntu/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41710:24)
    at async build (/home/ubuntu/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41552:16)
    at async CAC.<anonymous> (/home/ubuntu/caldera/plugins/magma/node_modules/vite/dist/node/cli.js:738:9)
Traceback (most recent call last):
  File "/home/ubuntu/caldera/server.py", line 249, in <module>
    subprocess.run(["npm", "run", "build"], cwd="plugins/magma", check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1.
```
<img width="1147" alt="image" src="https://github.com/mitre/caldera/assets/90907344/89041bcb-0aca-4959-aa2a-8b450bb4e120">

I have just followed the steps as mentioned in Concise installation steps.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by The-Reap-er** [comment]
i have the Same problem too on v5

**Comment by infosecconsultant** [comment]
It's missing the 'npm' package.
Try:
`sudo apt install npm`

**Comment by 0zk3y** [comment]
> It's missing the 'npm' package. Try: `sudo apt install npm`

NPM is already installed

<img width="961" alt="image" src="https://github.com/mitre/caldera/assets/90907344/767038ea-8d41-4067-bceb-7e6328cad693">

**Comment by plue0709** [comment]
![image](https://github.com/mitre/caldera/assets/80806913/14794db9-53cb-49dc-a9e6-35257319bb05)
Same !!! 
2 weeks ago i could run caldera but now i couldn't :(

**Comment by plue0709** [comment]
I fixed the problem. So, i use this way to fix the problem
``` 
sudo apt-get update

pip3 uninstall pyopenssl

pip3 install pyopenssl==22.0.0

pip3 uninstall cryptography

pip3 install cryptography==37.0.0
```
also required the newest version of npm

**Comment by elegantmoose** [comment]
So with using dockerfile, you needed to down version `cryptography` and install `pyopenssl`?

**Comment by plue0709** [comment]
yes, but so many bug with version 5.0.0 
I the webserver doesn't response when i login 
So i just use version 4.2.0

**Comment by 0zk3y** [comment]
> I fixed the problem. So, i use this way to fix the problem
> 
> ```
> sudo apt-get update
> 
> pip3 uninstall pyopenssl
> 
> pip3 install pyopenssl==22.0.0
> 
> pip3 uninstall cryptography
> 
> pip3 install cryptography==37.0.0
> ```
> 
> also required the newest version of npm

Tried using the same thing but still getting the same error, I don't believe it is something related to any python dependencies believe its something from node which is missing

<img width="907" alt="image" src="https://github.com/mitre/caldera/assets/90907344/bb44e147-5961-40dc-8f75-a0758b1298d1">

**Comment by plue0709** [comment]
you should use version 4.2.0

**Comment by 0zk3y** [comment]
Any update on Fixes?

**Comment by younggod69** [comment]
Hello! Try to install NodeJS v16 or later. This solved the issue for me. 
If it's not working, try to install NodeJS before npm.

source: https://caldera.readthedocs.io/en/latest/Installing-Caldera.html

**Comment by ZeKay** [comment]
for me, none of the above workarounds yielded anything, npm nodejs or unisntalling python ssl libraries. I then reinstalled 4.2.0

**Comment by sagen704** [comment]
I had the same issue using the branch install with 4.2.0 works.

**Comment by mgonzcast** [comment]
I can tell that I have tried installing branch 5.0.0 on Ubuntu 22.04 and I get the same errors with compiler-sfc. Any fix for this? 

Regarding Docker I could only got pulling this docker image from 3 years ago https://hub.docker.com/r/mitre/caldera but It uses Ubuntu 20.04.

I am a newbie with Caldera and I am finding a hard time to install it either on Ubuntu or Docker. Is there any clear pointer on the documentation?

**Comment by mgonzcast** [comment]
> you should use version 4.2.0

on which linux distribution? I have just tried with Ubuntu 20.04 and it fails when running the Magma build script

**Comment by mgonzcast** [comment]
> I had the same issue using the branch install with 4.2.0 works.

@sagen704 which linux distribution you are using?

**Comment by sagen704** [comment]
@mgonzcast I am using the most current version of kali Linux.

**Comment by fierytermite** [comment]
Running `npm i vue@3.2.25` fixed for me.

**Comment by mgonzcast** [comment]
> @mgonzcast I am using the most current version of kali Linux.

Thanks! That did the trick. Now I am struggling with some errors when I start caldera --insecure in kali 2024.2 running Caldera 4.2.0:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/caldera/plugins/fieldmanual/sphinx-docs/conf.py", line 28, in <module>
    import_plugin_docs(caldera_root_dir, sphinx_root_dir)
  File "/var/lib/caldera/plugins/fieldmanual/sphinx-docs/../../../plugins/fieldmanual/utils/plugin_docs.py", line 24, in import_plugin_docs
    doc_paths = copy_plugin_docs(caldera_root_dir, sphinx_root_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/caldera/plugins/fieldmanual/sphinx-docs/../../../plugins/fieldmanual/utils/plugin_docs.py", line 51, in copy_plugin_docs
    copied_files = copy_tree(plugin_docs_dir, sphinx_plugin_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/caldera/plugins/fieldmanual/sphinx-docs/../../../plugins/fieldmanual/utils/plugin_docs.py", line 17, in copy_tree
    before = set(glob.iglob(f"{dst}/**", recursive=True))
                 ^^^^
NameError: name 'glob' is not defined
```

But I can see the local caldera website. I am following the CTF training and some work and some don´t. For instance I can´t change the name of the agent or add an adversary with some abilities. Is there any to troubleshoot when the system shows an error?

**Comment by mgonzcast** [comment]
> Running `npm i vue@3.2.25` fixed it for me.

On which linux distribution?

**Comment by Chisom-1** [comment]
This is what i did that solved my problem 
 I installed node16 with this command

Obtain the Node.js source:
      curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -

Install the 16.x version of Node.js:
      sudo apt-get install -y nodejs

**Comment by mgonzcast** [comment]
At least when running Kali 2024.2 I am struggling installing version 5.0.0.
When I try to install requirements it complains a lot of python3 packages can't be installed.

I had to:

`apt remove python3-packaging python3-markdown python3-dnspython python3-rich python3-cryptography`

then again:

`pip3 install -r requirements.txt`

and install npm:

`apt install npm`

Now I could run:

`python3 server.py --insecure --build`

**Comment by nmlz** [comment]
I had the same error — in my case, it was caused by a version mismatch between vue, @vue/compiler-sfc, and @vitejs/plugin-vue, even though everything was newer than 3.2.25. Specifically, I was using:

`vue@3.5.13`
`@vue/compiler-sfc@3.5.13`
`@vitejs/plugin-vue@2.3.4`

To fix the issue, I downgraded Vue and its compiler to a compatible version:

```
npm uninstall vue @vue/compiler-sfc
npm install vue@3.2.47 @vue/compiler-sfc@3.2.47
```

After doing that, I ran into another build error related to pinia and vue-demi. If that happens to you too, this resolved it for me:

```
npm uninstall pinia
npm install pinia@2.0.36
```

Hope this helps someone

**Comment by altasnet** [comment]
> This is what i did that solved my problem I installed node16 with this command
> 
> Obtain the Node.js source: curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
> 
> Install the 16.x version of Node.js: sudo apt-get install -y nodejs

That's it ! Ubuntu 22 comes with very old nodejs, you need to upgrade it before running the server with --build
